#More info here https://github.com/Aiamded/WeatherEffect/wiki
#If you made a cool effect please also let me know ヽ(￣ω￣(￣ω￣〃)ゝ
enabled-list:
  sandstorm:
    ticks: 1
    attempts: 2
    weathertypes:
      - rain
    biomescheck: true
    biomes:
      - minecraft:badlands
    particle:
      enabled: true
      blockabovecheck: true
      aircheck: true
      blocktypes:
        - AIR
      types:
        - FALLING_DUST
      particledata: SAND
      delta-x: 2
      delta-y: 2
      delta-z: 2
      speed: 0
      count: 4
      radius: 5
      force: true
      chances: 100
    effects:
      enabled: true
      blockabovecheck: true
      types:
        - 2
        - 15
      duration: 60
      amplifier: 1
      isambient: false
      effectparticle: false
      chance: 100
    sound:
      enabled: true
      blockabovecheck: true
      name: ENTITY_HORSE_BREATHE
      pitch: 0.25
      radius: 15
      volume: 0.2
      chance: 50
    summon:
      enabled: false
      blockabovecheck: true
      entities-spawned-loggings: true
      #https://purpur.pl3x.net/javadoc/org/bukkit/entity/EntityType.html
      entities:
        - ZOMBIE
        - SKELETON
      #https://mcreator.net/wiki/entity-ids
      ##NBT implementation in progress.
      NBT:
        CanPickUpLoot:
          data: 1
          datatype: int
        NoAi: 0
      groundcheck:
        enabled: true
        depth: 10
      groundtypes:
        - SAND
        - RED_SAND
      aircheck:
        enabled: true
        height: 5
      blocktypes:
        - AIR
        - CAVE_AIR
      radius: 10
      #turned 0 to disable since the tickrate and attempts are too high even the chance = 1 still spawn to many entities
      chance: 1
  sandstorm-entity:
    ticks: 20
    attempts: 1
    weathertypes:
      - rain
    biomescheck: true
    biomes:
      - minecraft:badlands
    particle:
      enabled: false
    effects:
      enabled: false
    sound:
      enabled: false
    summon:
      enabled: true
      blockabovecheck: true
      entities-spawned-loggings: true
      entities:
        - ZOMBIE
        - SKELETON
      groundcheck:
        enabled: true
        depth: 10
      groundtypes:
        - SAND
        - RED_SAND
      aircheck:
        enabled: true
        height: 5
      blocktypes:
        - AIR
        - CAVE_AIR
      radius: 10
      #turned 0 to disable since the tickrate and attempts are too high even the chance = 1 still spawn to many entities
      chance: 1