name: WeatherEffect
version: 0.5
main: me.dummyperson.weathereffect.Main
api-version: 1.17
authors: [ Dummyperson, Aiamded, Kh Destruction ]
description: Customizable WeatherEffect generator. With Sound and Summon Entity Support.
website: www.breadstick.info
depend: [NBTAPI]

commands:
  weathereffect:
    description: WeatherEffect reload command
    permission: weathereffect.player
    usage: /<command>